// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package rdb

type Answer struct {
	ID             int64
	QuizManagerID  string
	QuestionNumber int64
	MusicName      string
}

type Artist struct {
	ID            int64
	QuizManagerID string
	Artist        string
}

type Choice struct {
	ID             int64
	QuizManagerID  string
	QuestionNumber int64
	Choice1        string
	Choice2        string
	Choice3        string
	Choice4        string
}

type Lyric struct {
	ID             int64
	QuizManagerID  string
	QuestionNumber int64
	Count          int64
	Lyrics         string
}

type QuizManager struct {
	ID                   int64
	UserID               string
	TheNumberOfQuestions int64
	QuizCount            int64
	LyricsCount          int64
	Status               string
	Type                 string
}
